SELECT CHAPTER.NAME AS NAME,
       CHAPTER.ID AS CHAPTER_ID,
       COUNT(CARD.ID) AS TOTAL_QUESTIONS,
       COUNT (CARD.ID) FILTER ( WHERE is_remembered) AS LEARNED_QUESTIONS
FROM CHAPTER
         LEFT JOIN CARD ON CHAPTER.ID = CARD.CHAPTER_ID
GROUP BY CHAPTER.ID;

SELECT CHAPTER.ID AS CHAPTER_ID,
       CHAPTER.NAME AS NAME
FROM CHAPTER;

INSERT INTO CHAPTER (NAME)
VALUES (?);

SELECT CARD.ID,
       CARD.QUESTION,
       CARD.ANSWER,
       CARD.IS_REMEMBERED
FROM CARD
WHERE CARD.ID=?;

INSERT INTO CARD (id, question, answer, is_remembered)
VALUES (?,?,?,?);

DELETE
FROM CARD
WHERE CARD.ID=?;

DELETE
FROM CHAPTER
WHERE CHAPTER.ID=?;

SELECT CARD.ID AS ID,
       CARD.QUESTION AS QUESTION,
       CARD.ANSWER AS ANSWER,
       CARD.IS_REMEMBERED AS REMEMBERED
FROM CARD
WHERE CARD.CHAPTER_ID = ?
  AND NOT CARD.IS_REMEMBERED
ORDER BY CARD.ID
LIMIT 1 OFFSET ?;

UPDATE CARD
SET IS_REMEMBERED = TRUE
WHERE CARD.ID = ?;

